In [47]:
import pandas as pd
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [48]:
df = pd.read_csv("IMDB Dataset.csv")

In [49]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [50]:
df['review'] = df['review'].str.lower()

In [51]:
def remove_html(data):
    if isinstance(data,str):
        import html
        import re 
        data = html.unescape(data)
        data  = re.sub(r'<[^>]+>', ' ',data)
        data  = re.sub(r'\s+', ' ',data)
        return data.strip()
    return data

In [52]:
df['review'] = df['review'].apply(remove_html)

In [53]:
punc = string.punctuation

In [54]:
def remove_pun(data):
    if isinstance(data, str):
        return ''.join(char for char in data if char not in punc)
    return data

In [55]:
df['review'] = df['review'].apply(remove_pun)

In [56]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production the filming tech...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the time of money is a ...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  im going to have to disagree with the previous...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [57]:
df['sentiment'].unique()

<StringArray>
['positive', 'negative']
Length: 2, dtype: str

In [58]:
stop_words = set(stopwords.words('english'))

In [59]:
def tokenize_text(text):
    if isinstance(text, str) and text.strip():
        return word_tokenize(text.lower())
    return []

In [60]:
df['tokens'] = df['review'].apply(tokenize_text)

In [61]:
df[['tokens','sentiment']].head()

                                              tokens sentiment
0  [one, of, the, other, reviewers, has, mentione...  positive
1  [a, wonderful, little, production, the, filmin...  positive
2  [i, thought, this, was, a, wonderful, way, to,...  positive
3  [basically, theres, a, family, where, a, littl...  negative
4  [petter, matteis, love, in, the, time, of, mon...  positive

In [62]:
def remove_stop_words(tokens):
    if isinstance(tokens,list):
        return [word for word in tokens if word.lower() not in stop_words]
    return []

In [63]:
df['stop_words_rem'] = df['tokens'].apply(remove_stop_words)

In [64]:
df

,review,sentiment,tokens,stop_words_rem
0,one of the other reviewers has mentioned that ...,positive,"[one, of, the, other, reviewers, has, mentione...","[one, reviewers, mentioned, watching, 1, oz, e..."
1,a wonderful little production the filming tech...,positive,"[a, wonderful, little, production, the, filmin...","[wonderful, little, production, filming, techn..."
2,i thought this was a wonderful way to spend ti...,positive,"[i, thought, this, was, a, wonderful, way, to,...","[thought, wonderful, way, spend, time, hot, su..."
3,basically theres a family where a little boy j...,negative,"[basically, theres, a, family, where, a, littl...","[basically, theres, family, little, boy, jake,..."
4,petter matteis love in the time of money is a ...,positive,"[petter, matteis, love, in, the, time, of, mon...","[petter, matteis, love, time, money, visually,..."
...,...,...,...,...
49995,i thought this movie did a down right good job...,positive,"[i, thought, this, movie, did, a, down, right,...","[thought, movie, right, good, job, wasnt, crea..."
49996,bad plot bad dialogue bad acting idiotic direc...,negative,"[bad, plot, bad, dialogue, bad, acting, idioti...","[bad, plot, bad, dialogue, bad, acting, idioti..."
49997,i am a catholic taught in parochial elementary...,negative,"[i, am, a, catholic, taught, in, parochial, el...","[catholic, taught, parochial, elementary, scho..."
49998,im going to have to disagree with the previous...,negative,"[im, going, to, have, to, disagree, with, the,...","[im, going, disagree, previous, comment, side,..."
49999,no one expects the star trek movies to be high...,negative,"[no, one, expects, the, star, trek, movies, to...","[one, expects, star, trek, movies, high, art, ..."

In [65]:
df.columns

Index(['review', 'sentiment', 'tokens', 'stop_words_rem'], dtype='str')

In [66]:
df[['review', 'sentiment', 'tokens', 'stop_words_rem']].iloc[0]

review            one of the other reviewers has mentioned that ...
sentiment                                                  positive
tokens            [one, of, the, other, reviewers, has, mentione...
stop_words_rem    [one, reviewers, mentioned, watching, 1, oz, e...
Name: 0, dtype: object