In [1]:
import pandas as pd
import string

In [2]:
df = pd.read_csv("IMDB Dataset.csv")

In [3]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [4]:
df['review'] = df['review'].str.lower()

In [5]:
def remove_html(data):
    if isinstance(data,str):
        import html
        import re 
        data = html.unescape(data)
        data  = re.sub(r'<[^>]+>', ' ',data)
        data  = re.sub(r'\s+', ' ',data)
        return data.strip()
    return data

In [6]:
df['review'] = df['review'].apply(remove_html)

In [7]:
punc = string.punctuation

In [8]:
def remove_pun(data):
    if isinstance(data, str):
        return ''.join(char for char in data if char not in punc)
    return data

In [10]:
df['review'] = df['review'].apply(remove_pun)

In [11]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production the filming tech...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the time of money is a ...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  im going to have to disagree with the previous...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [13]:
df['sentiment'].unique()

<StringArray>
['positive', 'negative']
Length: 2, dtype: str